.Dd August 31, 2022
.Dt WIFIBOX 8
.Os
.Sh NAME
.Nm wifibox
.Nd embedded (virtualized) wireless router
.Sh SYNOPSIS
.Nm
.Cm start
.Oo
.Cm guest
.Oc
.Nm
.Cm stop
.Oo
.Cm guest
.Oc
.Nm
.Cm restart
.Oo
.Cm guest | Cm netif | Cm console | Cm vmm
.Oc
.Nm
.Cm status
.Nm
.Cm console
.Nm
.Cm version
.Sh DESCRIPTION
.Nm
deploys a Linux guest operating system with the help of
.Xr bhyve 8
and attaches its driver to a wireless network device on the host system
via the PCI pass-through capabilities of the
.Xr vmm 4
kernel module.  This way the original FreeBSD PCI wireless network
card driver can be replaced for the performance and stability of the
one provided by the Linux kernel, or put into use if the device is not
supported by FreeBSD at all.
.Pp
Once the guest has been started up successfully,
.Nm
exposes the
.Sy wifibox0
.Xr bridge 4
networking interface, which needs to be configured further with the
help of
.Xr rc.conf 5 ,
so that the traffic could start flowing through the wireless card.
.Pp
There is a
.Nm
system service provided that can be used to start the appliance on boot
and stop on shutdown.
.Sh CONFIGURATION
After the installation to the system, check the sample configuration
files provided in the
.Pa %%PREFIX%%/etc/wifibox
directory and follow the instructions to create a working configuration,
otherwise
.Nm
will refuse to start.  For systems that might be put in sleep mode,
e.g. laptops, there is a sample
.Xr devd.conf 5
configuration file in the
.Pa %%PREFIX%%/etc/devd
directory that can be used to restart
.Nm
on resume.
.Pp
By default, PCI pass-through is disabled for AMD-based hardware, hence
it must be explicitly enabled via the corresponding
.Xr syctl 8
variable.  This can be done by adding the following line to either
.Pa /etc/sysctl.conf
or
.Pa /boot/loader.conf
depending on whether
.Xr vmm 4
is going to be loaded by
.Nm
or it is already loaded at boot.
.Bd -literal -offset indent
hw.vmm.amdvi.enable=1
.Ed
.Pp
In order to make
.Nm
work as a system service, the following line has to be added to
.Xr rc.conf 5 .
.Bd -literal -offset indent
wifibox_enable="YES"
.Ed
.Pp
At the same time, make sure that no FreeBSD driver is configured for
the same device and remove all the related settings from there.  The
.Xr devmatch 8
utility might be used to stop any conflicting drivers from loading
automatically.  For example, the
.Xr iwm 4
and
.Xr iwlwifi 4
native drivers could be disabled in
.Xr rc.conf 5
as shown below.
.Bd -literal -offset indent
devmatch_enable="YES"
devmatch_blocklist="if_iwm if_iwlwifi"
.Ed
.Pp
Note these settings will only take effect on the next boot.  Until
then the
.Nm devmatch
service must be started and the drivers should be removed manually by
using
.Xr kldunload 8 .
.Bd -literal -offset indent
# service devmatch start
# kldunload if_iwm if_iwlwifi
.Ed
.Pp
The
.Nm
service can be then started up as follows.
.Bd -literal -offset indent
# service wifibox start
.Ed
.Pp
After
.Nm
started successfully, the IP address for the corresponding networking
interface needs to be configured in
.Xr rc.conf 5 .
For example, assignment of a dynamic IP address can be requested by
adding this line below.
.Bd -literal -offset indent
ifconfig_wifibox0="SYNCDHCP"
.Ed
.Pp
In addition to this, to reduce boot times,
.Xr dhclient 8
can be instructed to run in the background and not to wait for a
positive link and issuing an IP address after it has been launched.
.Bd -literal -offset indent
background_dhclient_wifibox0="YES"
defaultroute_delay="0"
.Ed
.Pp
If preferred, static IP address configuration is possible with this
method.  Assume that
.Sy wifibox0
is configured as 10.0.0.1/24 on the guest's side, and the host wants
to use the 10.0.0.2/24 IP address.
.Bd -literal -offset indent
defaultrouter="10.0.0.1"
ifconfig_wifibox0="inet 10.0.0.2/24"
.Ed
.Pp
The
.Sy wifibox0
networking interface can be brought up with the use of the
.Nm netif
service.
.Bd -literal -offset indent
# service netif start wifibox0
.Ed
.Pp
For static IP address configurations, the
.Nm routing
service has to be restarted as well.
.Bd -literal -offset indent
# service routing restart
.Ed
.Pp
Note that since
.Sy wifibox0
becomes managed by
.Nm netif
this way,
.Nm
has to be restarted every time when the networking interfaces are
recreated by
.Nm netif ,
otherwise the link will stop working.
.Bd -literal -offset indent
# service netif stop
# service wifibox restart
# service netif start
.Ed
.Pp
If the
.Xr devd.conf 5
file is installed,
.Xr devd 8
must be restarted so the additional configuration file can be read.
.Bd -literal -offset indent
# service devd restart
.Ed
.Sh COMMANDS
The
.Nm
system service and
.Xr devd 8
can manage the following actions by themselves, but the commands for the
.Nm
script itself are listed below for the reference.
.Bl -tag -width -indent
.It Cm start Oo Cm guest Oc
Start
.Nm .
By default, the
.Sy wifibox0
interface is created and the guest is attached to the configured PCI
wireless network device.  The network interface of the FreeBSD driver
on the same device must not be configured.  When the
.Cm guest
parameter is given, only the guest is started.  Note that this can
work only if
.Sy wifibox0
networking interface has already been created.
.It Cm stop Oo Cm guest Oc
Stop
.Nm .
Without the
.Cm guest
parameter, the
.Sy wifibox0
interface is destroyed and the guest is detached from the configured
PCI wireless network device.  After that, the FreeBSD driver is free
to take over the device.  When the
.Cm guest
parameter is specified, only the guest is stopped, and the
.Sy wifibox0
interface is kept alive for later re-use.
.It Cm restart Oo Cm guest | Cm netif | Cm console | Cm vmm Oc
Restart
.Nm ,
which is the sequential composition of the
.Cm stop
and
.Cm start
commands by default.  It is possible to specify a target, therefore
limit the scope of this operation in different ways.
.Bl -tag -width "console"
.It Cm guest
Restart the guest only, maintain the console device and the networking
interface.  This is recommended for applying system-level updates to
the guest.
.It Cm netif
Recreate the networking interface and restart the guest.  That latter
is required because the networking interface is bound to the virtual
machine that runs the guest.
.It Cm console
Recreate the null-modem device and restart the guest.  That latter is
required because the null-modem device is bound to the virtual machine
that runs the guest.  This is recommended when the console support is
turned on in the configuration.
.It Cm vmm
Restart the guest while reloading the
.Xr vmm 4
kernel module, maintain the console device and the networking
interface.  This is a workaround for the guest to recover from a state
where the wireless device becomes unresponsive after the ACPI resume
event.
.El
.It Cm status
Check and display if
.Nm
is still running.
.It Cm console
Attach to the running guest with
.Xr cu 1
through a virtual serial port, implemented by
.Xr nmdm 4 .
This is recommended for troubleshooting problems with the guest in an
interactive fashion.  It can also be used to perform updates, install
or remove packages.  This has to be configured specifically in order
to work.  The actual way of logging into the system as an
administrator depends on the VM image in use.  Most of the time the
.Sy root
user with a blank password works.  See
.Xr wifibox-guest 5
for more information.
.It Cm version
Display version of
.Nm
and the SHA-256 hash of the guest disk image.  The output is suitable
for reporting errors.  Note that custom images are not supported.
.Sh DIAGNOSTICS
If
.Nm
does not have behave in the expected way, check
.Pa /var/log/wifibox.log
for errors.  This file holds messages about the progress of each
executed command, and their amount depends on the configured level of
logging.  The log files of the guest are exported to the host and they
are made available under the
.Pa /var/run/wifibox/appliance/log
directory.  There it is recommended to check the
.Pa /var/run/wifibox/appliance/log/dmesg
file for messages related to the boot sequence, such as driver
initialization, and the
.Pa /var/run/wifibox/appliance/log/messages
file for the run-time system messages, which are usually emitted
by the daemons.  If all else fails, use the
.Cm console
command to connect to the guest.
.Sh EXIT STATUS
The exit status is 0 on success, and >0 if any of the commands fail.
.Sh SEE ALSO
.Xr bhyve 8 ,
.Xr vmm 4 ,
.Xr bridge 4 ,
.Xr sysctl 8 ,
.Xr sysctl.conf 5 ,
.Xr loader.conf 5 ,
.Xr rc.conf 5 ,
.Xr devmatch 8 ,
.Xr kldunload 8 ,
.Xr devd.conf 5 ,
.Xr devd 8 ,
.Xr cu 1 ,
.Xr nmdm 4 ,
.Xr wifibox-guest 5
.Sh CAVEATS
.Nm
supports only a single wireless network device at a time, and it has
to be PCI one.  It cannot be launched multiple times.
.Pp
The
.Cm restart vmm
command should be used with caution, because it may crash the system
when it has not been in a sleep state.  Hence it is best to use in
combination with
.Xr devd 8 .
.Pp
The
.Cm restart vmm
command will not probably work on systems where other
.Xr bhyve 8
guests are running in parallel as
.Xr vmm 4
kernel module could not be unloaded in such cases.
.Pp
The
.Cm restart vmm
command may not work properly on some systems and its repeated use can
cause the PCI device to be lost completely until the next boot.  As a
workaround, it is worth to use the combination of
.Cm stop guest
(on suspend) and
.Cm start guest
(on resume) instead.
.Pp
The PCI pass-through implementation of
.Xr bhyve 8
may not be able to cooperate with the Linux system in the guest due to
lack of emulation of certain quirks and features that are required to
make the driver work.  Sometimes this can cause strange and unexpected
error messages.  Always try the latest available version of
.Xr bhyve 8
when this happens.
.Sh AUTHORS
.An Gábor Páli Aq Mt pali.gabor@gmail.com
