.Dd September 16, 2021
.Dt WIFIBOX 8
.Os
.Sh NAME
.Nm wifibox
.Nd embedded (virtualized) wireless router
.Sh SYNOPSIS
.Nm
.Cm start
.Nm
.Cm stop
.Nm
.Cm restart
.Nm
.Cm status
.Nm
.Cm resume
.Nm
.Cm console
.Nm
.Cm version
.Sh DESCRIPTION
.Nm
deploys a Linux guest operating system with the help of
.Xr bhyve 8
and attaches its driver to a wireless network device on the host system
via the PCI pass-through capabilities of the
.Xr vmm 4
kernel module.  This way the original FreeBSD PCI wireless network
card driver can be replaced for the performance and stability of the
one provided by the Linux kernel, or put into use if the device is not
supported by FreeBSD at all.
.Pp
Once the guest has been started up successfully,
.Nm
exposes the
.Sy wifibox0
.Xr bridge 4
networking interface, which needs to be configured further with the
help of
.Xr rc.conf 5 ,
so that the traffic could start flowing through the wireless card.
.Pp
There is a
.Nm
system service provided that can be used to start the appliance on boot
and stop on shutdown.
.Sh CONFIGURATION
After the installation to the system, check the sample configuration
files provided in the
.Pa %%PREFIX%%/etc/wifibox
directory and follow the instructions to create a working configuration,
otherwise
.Nm
will refuse to start.  For systems that might be put in sleep mode,
e.g. laptops, there is a sample
.Xr devd.conf 5
configuration file in the
.Pa %%PREFIX%%/etc/devd
directory that can be used to restart
.Nm
on resume.
.Pp
In order to make
.Nm
work as a system service, the following line has to be added to
.Xr rc.conf 5 .
.Bd -literal -offset indent
wifibox_enable="YES"
.Ed
.Pp
At the same time, make sure that no FreeBSD driver is configured for
the same device and remove all the related settings from there.  The
.Nm
service can be then started up as follows.
.Bd -literal -offset indent
# service wifibox start
.Ed
.Pp
After
.Nm
started successfully, the IP address for the corresponding networking
interface needs to be configured in
.Xr rc.conf 5 .
For example, assignment of a dynamic IP address can requested by
adding this line below.
.Bd -literal -offset indent
ifconfig_wifibox0="SYNCDHCP"
.Ed
.Pp
If preferred, static IP address configuration is possible with this
method, which can be faster.  Assume that
.Sy wifibox0
is configured as 10.0.0.1/24 on the guest's side, and the host wants
to use the 10.0.0.2/24 IP address.
.Bd -literal -offset indent
defaultrouter="10.0.0.1"
ifconfig_wifibox0="inet 10.0.0.2/24"
.Ed
.Pp
The
.Sy wifibox0
networking interface can be brought up with the use of the
.Nm netif
service.
.Bd -literal -offset indent
# service netif start wifibox0
.Ed
.Pp
For static IP address configurations, the
.Nm routing
service has to be restart as well.
.Bd -literal -offset indent
# service routing restart
.Ed
.Pp
If the
.Xr devd.conf 5
file is installed,
.Xr devd 8
must be restarted so the additional configuration file can be read.
.Bd -literal -offset indent
# service devd restart
.Ed
.Sh COMMANDS
The
.Nm
system service and
.Xr devd 8
can manage the following actions by themselves, but the commands for the
.Nm
script itself are listed below for the reference.
.Bl -tag -width -indent
.It Cm start
Start
.Nm .
The
.Sy wifibox0
interface is created and the guest is attached to the configured
PCI wireless network device.  The network interface of the FreeBSD
driver on the same device must not be configured.
.It Cm stop
Stop
.Nm .
The
.Sy wifibox0
interface is destroyed and the guest is detached from the configured
PCI wireless network device.  After that, the FreeBSD driver is free
to take over the device.
.It Cm restart
Restart
.Nm ,
which is a sequential composition of the
.Cm stop
and
.Cm start
commands.
.It Cm status
Check and display if
.Nm
is still running.
.It Cm resume
Apply a workaround for the guest to recover from a state where the
wireless device becomes unresponsive after the ACPI resume event.
This involves reloading the
.Xr vmm 4
kernel module and restarting the guest.
.It Cm console
Attach to the running guest with
.Xr cu 1
through a virtual serial port, implemented by
.Xr nmdm 4 .
This is recommended for troubleshooting problems with the guest in an
interactive fashion.  It can also be used to perform updates, install
or remove packages.  This has to be configured specifically in order
to work.  The actual way of logging into the system as an
administrator depends on the VM image in use.  Most of the time the
.Sy root
user with a blank password works.
.It Cm version
Display version of
.Nm
and the SHA-256 hash of the guest disk image.  The output is suitable
for reporting errors.  Note that custom images are not supported.
.Sh DIAGNOSTICS
If the guest cannot start up due to problems with
.Xr bhyve 4 ,
check the
.Pa /var/log/wifibox/bhyve.log
and
.Pa /var/log/wifibox/grub-bhyve.log
files for errors.  The log files of the guest are exported to the host
and they are made available under the
.Pa /var/run/wifibox/appliance/log
directory.  There it is recommend to check the
.Pa /var/run/wifibox/appliance/log/dmesg
file for messages related to the boot sequence, such as driver
initialization, and the
.Pa /var/run/wifibox/appliance/log/messages
file for the run-time system messages, which are usually emitted
by the daemons.  If all else fails, use the
.Cm console
command to connect to the guest.
.Sh EXIT STATUS
The exit status is 0 on success, and >0 if any of the commands fail.
.Sh SEE ALSO
.Xr bhyve 8 ,
.Xr vmm 4 ,
.Xr bridge 4 ,
.Xr rc.conf 5 ,
.Xr devd.conf 5 ,
.Xr devd 8 ,
.Xr cu 1 ,
.Xr nmdm 4
.Sh CAVEATS
.Nm
supports only a single wireless network device at a time, and it has
to be PCI one.  It cannot be launched multiple times.
.Pp
The
.Cm resume
command should be used with caution, because it may crash the system
when it has not been a sleep state.  Hence it is best to use in
combination with
.Xr devd 8 .
.Pp
The
.Cm resume
command will not probably work on systems where other
.Xr bhyve 8
guests are running in parallel as
.Xr vmm 4
kernel module could not be unloaded in such cases.
.Sh AUTHORS
.An Gábor Páli Aq Mt pali.gabor@gmail.com
