#! /bin/sh
# shellcheck disable=SC3043

PREFIX=%%PREFIX%%
LOCALBASE=%%LOCALBASE%%
VERSION=%%VERSION%%
SCRIPT=${PREFIX}/sbin/wifibox
LOGDIR=/var/log/wifibox
RUNDIR=/var/run/wifibox
CONFDIR=${PREFIX}/etc/wifibox
BHYVE_LOG=${LOGDIR}/bhyve.log
GRUB_BHYVE_LOG=${LOGDIR}/grub-bhyve.log

: "${BHYVE:=/usr/sbin/bhyve}"
: "${BHYVECTL:=/usr/sbin/bhyvectl}"
: "${DEVCTL:=/usr/sbin/devctl}"
: "${IFCONFIG:=/sbin/ifconfig}"
: "${SYSCTL:=/sbin/sysctl}"
: "${DHCLIENT:=/sbin/dhclient}"
: "${KLDLOAD:=/sbin/kldload}"
: "${KLDUNLOAD:=/sbin/kldunload}"
: "${KLDSTAT:=/sbin/kldstat}"
: "${SHA256:=/sbin/sha256}"

: "${CAT:=/bin/cat}"
: "${ECHO:=/bin/echo}"
: "${PRINTF:=/usr/bin/printf}"
: "${GREP:=/usr/bin/grep}"
: "${SED:=/usr/bin/sed}"
: "${SLEEP:=/bin/sleep}"
: "${PGREP:=/bin/pgrep}"
: "${KILL:=/bin/kill}"
: "${RM:=/bin/rm}"

: "${GRUB_BHYVE:=${LOCALBASE}/sbin/grub-bhyve}"

DISK_IMAGE="${PREFIX}/share/wifibox/disk.img"

check_virtfs() {
    if ! (${BHYVE} -s help | ${GREP} -Fq virtio-9p); then
	${ECHO} "ERROR: The Virtio 9p (VirtFS) bhyve interface is not available."
	exit 127
    fi
}

sysctl_value() {
    ${SYSCTL} -nq "$1"
}

check_vmm() {
    if ! ${KLDSTAT} -q -m vmm; then
	${ECHO} "ERROR: vmm.ko is not loaded."
	exit 127
    fi
}

# shellcheck disable=SC2046
check_iommu() {
    local _iommu
    local _amdvi

    _iommu=$(sysctl_value "hw.vmm.iommu.enable" || ${ECHO} "0")
    _amdvi=$(sysctl_value "hw.vmm.amdvi.enable" || ${ECHO} "0")

    if [ "${_iommu}" -eq "0" ] && [ "${_amdvi}" -eq "0" ]; then
	${ECHO} "ERROR: PCI pass-through is not available for bhyve."
	exit 127
    fi
}

assert_vm_can_run() {
    check_vmm
    check_iommu
    check_virtfs
}

get_image_checksum() {
    ${SHA256} -q "${DISK_IMAGE}"
}

check_configuration() {
    local _file="$1"

    if [ ! -f "${_file}" ]; then
	${ECHO} "ERROR: ${_file} is missing, please create it from the sample."
	exit 3
    fi
}

create_interfaces() {
    ${IFCONFIG} bridge create name bridge-wifibox up > /dev/null
    ${IFCONFIG} tap create name tap-wifibox > /dev/null
    ${IFCONFIG} bridge-wifibox addm tap-wifibox > /dev/null
}

destroy_interfaces() {
    ${IFCONFIG} bridge-wifibox destroy > /dev/null
    ${IFCONFIG} tap-wifibox destroy > /dev/null
}

get_ppt_device() {
    check_configuration "${CONFDIR}/bhyve.conf"

    # shellcheck source=./etc/bhyve.conf.sample
    . "${CONFDIR}/bhyve.conf"

    ${ECHO} "pci${passthru}" | ${SED} 's!/!:!g'
}

get_vm_pid() {
    ${PGREP} -fx "bhyve[: ].* wifibox"
}

vm_start() {
    check_configuration "${CONFDIR}/bhyve.conf"
    check_configuration "${CONFDIR}/interfaces.conf"
    check_configuration "${CONFDIR}/udhcpd.conf"
    check_configuration "${CONFDIR}/wpa_supplicant.conf"

    # shellcheck source=./etc/bhyve.conf.sample
    . "${CONFDIR}/bhyve.conf"

    ${DEVCTL} set driver -f "$(get_ppt_device)" ppt > /dev/null
    ${GRUB_BHYVE} -S -M "${memory}" -r host \
		  -m ${PREFIX}/share/wifibox/device.map \
		  -d ${PREFIX}/share/wifibox \
		  wifibox > ${GRUB_BHYVE_LOG} 2>&1
    ${BHYVE} -c "${cpus}" -m "${memory}" -AHP -u -S \
	     -s 0,hostbridge \
	     -s 31,lpc \
	     -s 4:0,virtio-blk,${DISK_IMAGE} \
	     -s 4:1,virtio-9p,config=${CONFDIR},ro \
	     -s 4:2,virtio-9p,var=${RUNDIR}/appliance \
	     -s 5:0,e1000,tap-wifibox \
	     -s 6:0,passthru,"${passthru}" \
	     wifibox > ${BHYVE_LOG} 2>&1 &
    # Give some time for bhyve to launch.
    ${SLEEP} 1 > /dev/null

    if [ -z "$(get_vm_pid)" ]; then
	destroy_interfaces
	${ECHO} "ERROR: Guest could not be started, check the contents of ${BHYVE_LOG}."
	exit 4
    fi
}

vm_stop() {
    ${KILL} -SIGTERM "$(get_vm_pid)" > /dev/null
    ${SLEEP} 3 > /dev/null
    ${BHYVECTL} --force-poweroff --vm=wifibox >> ${BHYVE_LOG} 2>&1
    ${BHYVECTL} --destroy --vm=wifibox >> ${BHYVE_LOG} 2>&1
    ${SLEEP} 1 > /dev/null
    ${DEVCTL} clear driver -f "$(get_ppt_device)" > /dev/null
}

assert_vm_runs() {
    if [ -z "$(get_vm_pid)" ]; then
	${ECHO} "wifibox is not running."
	exit 1
    fi
}

show_progress() {
    ${PRINTF} "."
}

wifibox_start() {
    local _pid

    assert_vm_can_run

    _pid="$(get_vm_pid)"
    if [ -n "${_pid}" ]; then
	${ECHO} "wifibox is already running as PID ${_pid}."
	exit 1
    fi

    ${PRINTF} "Launching wifibox"

    create_interfaces
    show_progress

    vm_start
    show_progress

    # Give some more time for the guest to boot up.
    ${SLEEP} 2 > /dev/null
    ${ECHO} "OK"

    ${DHCLIENT} bridge-wifibox
}

wifibox_stop() {
    assert_vm_runs

    ${PRINTF} "Stopping wifibox"

    vm_stop
    show_progress

    destroy_interfaces
    show_progress

    ${ECHO} "OK"
}

# This is a workaround to recover from the unfortunate state of the
# wireless device after resume.
kick_vmm() {
    if ! ${KLDUNLOAD} vmm; then
	${ECHO} "ERROR: Some bhyve guests are still running, vmm.ko could not be unloaded."
	exit 127
    fi
    ${KLDLOAD} vmm
}

wifibox_resume() {
    assert_vm_runs

    ${PRINTF} "Resuming wifibox"

    vm_stop
    show_progress

    ${SLEEP} 1
    kick_vmm
    show_progress

    vm_start
    ${ECHO} "OK"
}

wifibox_restart() {
    wifibox_stop
    wifibox_start
}

wifibox_status() {
    local _pid

    _pid="$(get_vm_pid)"
    if [ -n "${_pid}" ]; then
	${ECHO} "wifibox is running as PID ${_pid}."
    else
	${ECHO} "wifibox is not running."
	return 1
    fi
}

wifibox_version() {
    ${ECHO} "wifibox version ${VERSION}"
    ${ECHO} "Disk image checksum: $(get_image_checksum)"
}

# Do not execute the main program when sourced.
[ "$0" != "${SCRIPT}" ] && return 0

case "$1" in
    start) wifibox_start;;
    stop) wifibox_stop;;
    resume) wifibox_resume;;
    restart) wifibox_restart;;
    status) wifibox_status;;
    version) wifibox_version;;
    *) ${ECHO} "USAGE: ${SCRIPT} start | stop | restart | resume | status | version" ;;
esac
