name: Manual page linter
on:
  push:
    paths:
      - 'man/**'
      - '.github/workflows/man.yml'

jobs:
  Checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install -y igor

        run: |
          make VERSION=9.9.9 mancheck
