name: ShellCheck
on:
  push:
    paths:
      - 'sbin/**'
      - '.github/workflows/shellcheck.yml'

jobs:
  Checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install -y hs-ShellCheck

        run: |
          make VERSION=9.9.9 shellcheck
